routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('company','CompanyController');
Route::resource('employee','EmployeeController');
Route::any('company/dt', 'CompanyController@usersList')->name('company.datatable'); 
Route::any('employee/dt', 'EmployeeController@usersList')->name('employee.datatable'); 

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Datatables;
use DB;
use Validator;
use App\Companies;
use App\Employees;
class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('company.index');
    }

    public function usersList(){
        
        $users = DB::table('companies')->select('*');
        return datatables()->of($users)
        ->addIndexColumn()
                    ->addColumn('action', function($row) {
                           $btn = '<a href="javascript:void(0)" class="edit btn btn-primary btn-sm"  id="edit-customer"  data-id="'.$row->id.'">Update</a> <a href="javascript:void(0)" id="delete-customer" data-id="'.$row->id.'" class="edit btn btn-primary btn-sm">Delete</a>';
                           return $btn;
                    })
                    ->rawColumns(['action'])
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        if($request->btnsave =="create-customer"){
        $validator = Validator::make(
            $request->all(),
            [
            'name'     => 'required|alpha',
            'mobile'     => 'required',
            'email'     => 'required',
            ]);
        if ($validator->fails()) {
            return response()->json($validator->errors(), 406);
        }
        $profileImage ='';
        if ($files = $request->file('profile_image')) {
            // Define upload path
            $destinationPath = public_path('/profile_images/'); // upload path
         // Upload Orginal Image           
            $profileImage = date('YmdHis') . "." . $files->getClientOriginalExtension();
            $files->move($destinationPath, $profileImage);
 
            
         }
        $admin = new Companies();
        $admin->name = $request->name;
        $admin->email = $request->email;
        $admin->mobile = $request->mobile;
        $admin->logo = $profileImage;
        $admin->save();
       
			$msg = 'Company data is created successfully';
		return redirect()->route('company.index')->with('success',$msg);
    }else{
        $affected = DB::table('companies')
              ->where('id', $request->cust_id)
              ->update(['name' => $request->name,'email' => $request->email,'mobile' => $request->mobile]);
              $msg = 'Company data is update successfully';
		return redirect()->route('company.index')->with('success',$msg);
    }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $where = array('id' => $id);
		$customer = Companies::where($where)->first();
		return response()->json([
            "data" => $customer,]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $exist = Employees::where('company_name',$id)->first();
        if(empty($exist)){
            Companies::find($id)->delete($id);
    
            return response()->json([
                'success' => 'Record deleted successfully!'
            ]);
        }
        return response()->json([
            'success' => 'already used!'
        ]);
    }
}

resources/views/company/index.blade.php
<!DOCTYPE html>
 
<html lang="en">
<head>
<title>Company list</title>
<meta name="csrf-token" content="{{ csrf_token() }}">
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">  
<link  href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet">
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>  
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/5.5.2/bootbox.min.js"></script>
</head>
      <body>
         <div class="container">
               <h2>Company list</h2>
               @if(session()->has('success'))
                  <div class="alert alert-success">
                     {{ session()->get('success') }}
                  </div>
               @endif
               @if(session()->has('error'))
                  <div class="alert alert-danger">
                     {{ session()->get('error') }}
                  </div>
               @endif
               <div class="pull-right">
               <a href="{{ route('home') }}" class="btn btn-danger">Back</a>
               <a href="javascript:void(0)" class="btn btn-success mb-2" id="new-customer" data-toggle="modal">New Company</a>
               </div>
            <table class="table table-bordered" id="laravel_datatable">
               <thead>
                  <tr>
                     <th>Id</th>
                     <th>Name</th>
                     <th>Email</th>
                     <th>Mobile</th>
                     <th>Action</th>
                  </tr>
               </thead>
            </table>
            <div class="modal fade" id="crud-modal" aria-hidden="true" >
<div class="modal-dialog">
<div class="modal-content">
<div class="modal-header">
<h4 class="modal-title" id="customerCrudModal"></h4>
</div>
<div class="modal-body">
<form name="custForm" id="formId" action="{{ route('company.store') }}" method="POST" enctype="multipart/form-data">
<input type="hidden" name="cust_id" id="cust_id" >
@csrf
<div class="row">
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>Name:</strong>
<input type="text" name="name" id="name" class="form-control" placeholder="Name" onchange="validate()" >
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>Email:</strong>
<input type="text" name="email" id="email" class="form-control" placeholder="Email" onchange="validate()">
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>Mobile:</strong>
<input type="text" name="mobile" id="mobile" class="form-control" placeholder="Mobile" onchange="validate()" onkeypress="validate()">
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>logo:</strong>
<input type="file" name="profile_image" id="profile_image"  class="form-control">
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 text-center">
<button type="submit" id="btn-save" name="btnsave" class="btn btn-primary" disabled>Submit</button>
<a href="{{ route('company.index') }}" class="btn btn-danger">Cancel</a>
</div>
</div>
</form>
</div>
</div>
</div>
</div>
         </div>
   <script>
   $(document).ready( function () {
    $('#laravel_datatable').DataTable({
           processing: true,
           serverSide: true,
           ajax: {
                url: '{!! route('company.datatable') !!}',
                type: 'post',
                headers: {
                    'X-CSRF-TOKEN': '{{ csrf_token() }}'
                },
                data: function (d) {
                    
                }
            },
           columns: [
                    { data: 'id', name: 'id' },
                    { data: 'name', name: 'name' },
                    { data: 'email', name: 'email' },
                    { data: 'mobile', name: 'mobile' },
                    {data: 'action', name: 'action', orderable: false, searchable: false},
                 ]
        });
     });
     $('#new-customer').click(function () {
$('#btn-save').val("create-customer");
$('#customer').trigger("reset");
$('#customerCrudModal').html("Add New Customer");
$('#crud-modal').modal('show');
});
/* Delete customer */
$('body').on('click', '#delete-customer', function () {
    var id = $(this).data("id");
        var token = $("meta[name='csrf-token']").attr("content");
    
        $.ajax(
        {
            url: "company/"+id,
            type: 'DELETE',
            data: {
                "id": id,
                "_token": token,
            },
            success: function (data){
               
               bootbox.alert(data.success);
            }
        });
   
});
/* Edit customer */
$('body').on('click', '#edit-customer', function () {
   
      var customer_id = $(this).data('id');
      $.get('company/'+customer_id+'/edit', function (data) {
         console.log(data.data.first_name);
      $('#customerCrudModal').html("Edit company");
      $('#btn-update').val("Update");
      $('#btn-save').prop('disabled',false);
      $('#crud-modal').modal('show');
      $('#cust_id').val(data.data.id);
      $('#name').val(data.data.name);
      $('#email').val(data.data.email);
      $('#mobile').val(data.data.mobile);
      $("#profile_image").hide();
      })
    });

function validate()
{
	if(document.custForm.name.value !='' && document.custForm.email.value !='' && document.custForm.mobile.value !='')
	    document.custForm.btnsave.disabled=false
	else
		document.custForm.btnsave.disabled=true
}
  </script>
   </body>
</html>